### ISSUE TITLE
zip archive is invalid

### ISSUE THREAD

**Issue by kravchukdv** [anticensority/decrab-youtube#10]
При попытке выполнить пункты 
_Переименуйте название-расширения.crx в название-расширения.zip.
Распакуйте .zip-архив в отдельную папку._
пишет что zip archive is invalid.

**Comment by ilyaigpetrov** [comment]
В крайнем случае можно скачать zip-архив с исходниками.
![decrab-assets-zip-source](https://github.com/user-attachments/assets/f8b66c88-7c89-4afc-8d42-9c2099bba95b)
