### ISSUE TITLE
CMD не находит chrome.exe 

### ISSUE THREAD

**Issue by ChumbaShpek** [anticensority/decrab-youtube#7]
![image](https://github.com/user-attachments/assets/e2c32dbc-fbc8-4760-b4a4-a04392f7812b)
![image](https://github.com/user-attachments/assets/63395137-891f-48a5-be30-da05a5f5b0ea)

Делал всё по инструкции, уточнений никаких нет, может криво что то скопировал?

C:\Program Files\Google\Chrome\Application\chrome.exe chrome.exe --disable-web-security --user-data-dir=C:\tmpDirForChrome

почему выдает ошибку?

**Comment by ilyaigpetrov** [comment]
С кавычкми и без повторения `chrome.exe` дожно сработать:
```sh-session
"C:\Program Files\Google\Chrome\Application\chrome.exe" --disable-web-security --user-data-dir=C:\tmpDirForChrome
```
Заметьте, что в строке "Program Files" есть пробел. Команды с пробелами должны быть заключены в двойные кавычки.
