### ISSUE TITLE
Непонятные и противоречивые инструкции

### ISSUE THREAD

**Issue by digitalsimulator** [anticensority/decrab-youtube#9]
Вот здесь у вас инструкция по установке расширения в браузер [https://github.com/anticensority/decrab-youtube/releases/tag/v0.0.1](url) 
Хорошо. Тогда вот это что за инструкция? [https://github.com/anticensority/decrab-youtube/blob/main/README.md](url)
Кроме того, во второй инстукции есть п.5 

> Перетащить на открытую в п.2 вкладку .crx-файл, скачанный из раздела [Releases](https://github.com/anticensority/decrab-youtube/releases) данного репозитория на GitHub (ищите справа).

Но п.2 не существует. Есть  2) Откроется терминал. Введите в него (без $): Или имелось в виду п.3?

**Comment by Verity-Freedom** [comment]
У меня вообще не Хром (по понятным причинам; скоро на Хроме вообще mv2 отключат), мне там crx не получается перетаскивать. Можно установить папкой (загрузкой распакованного) или запуском crx через экзешник.

**Comment by Verity-Freedom** [comment]
Хотелось бы какую-то инструкцию для запуска через ярлык или типа того.

**Comment by ilyaigpetrov** [comment]
@digitalsimulator, спасибо, поправил.

@Verity-Freedom,
> Можно установить [...] запуском crx через экзешник.

Как это делается? Просто двойной щелчёк мышки по .crx-файлу? Переносом .crx-файла на `chrome.exe`?

**Comment by Verity-Freedom** [comment]
> Как это делается? Просто двойной щелчёк мышки по .crx-файлу? Переносом .crx-файла на `chrome.exe`?

Ну да я всегда запускал crx через двойной щелчок мыши, если точнее то через выбор "открыть как", чтобы был выбор открывать crx через разные браузеры, а перетаскивание у меня не сработало, но я стараюсь отвязаться от Гугл Хрома, я даже программисту одному платил чтобы мне мой браузер для меня переделали. Также есть вариант загрузить распакованное, но в таком случае браузер будет жаловаться, что установлено расширение некорректно.
